name: Auto Close, Delete, and Lock Pull Requests

on:
  schedule:
    - cron: '0 0 * * 1-5'  # Executa toda segunda-feira à meia-noite
  workflow_dispatch:  # Permite execução manual

permissions:
  contents: write
  pull-requests: write

jobs:
  close_delete_lock_pull_requests:
    runs-on: ubuntu-latest

    steps:
      - name: Close, Delete, and Lock Pull Requests in All Repositories
        env:
          GITHUB_TOKEN: ${{ secrets.PULL_REQUESTS_CHECKING_TOKEN }}  # Certifique-se de que este token tenha permissões corretas
          ORG_NAME: cyonicsolutions-cluster  # Nome da organização
        run: |
          # Obtenha todos os repositórios da organização
          REPOS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/orgs/$ORG_NAME/repos?per_page=100" | jq -r '.[].full_name')

          for REPO_NAME in $REPOS; do
            echo "Checking pull requests in $REPO_NAME"

            # Busque todas as pull requests abertas no repositório atual
            OPEN_PRS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$REPO_NAME/pulls" | jq -r '.[].number')

            for PR_NUMBER in $OPEN_PRS; do
              echo "Processing Pull Request #$PR_NUMBER in repository $REPO_NAME"

              # Defina a mensagem de fechamento
              CLOSE_MESSAGE="**Pull request submissions are not accepted.**\n\nPlease visit https://github.com/getcyonic/$REPO_NAME/pulls and submit your pull request there with the same content.\nThank you!"

              # Comente no pull request
              curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
                -d "{\"body\": \"$CLOSE_MESSAGE\"}" \
                "https://api.github.com/repos/$REPO_NAME/issues/$PR_NUMBER/comments" || echo "Failed to comment on pull request #$PR_NUMBER"

              # Fecha o pull request
              curl -s -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
                -d "{\"state\": \"closed\"}" \
                "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER" || echo "Failed to close PR #$PR_NUMBER"

              echo "Closed pull request #$PR_NUMBER in $REPO_NAME."

              # Bloqueia a conversa
              curl -s -X PUT -H "Authorization: token $GITHUB_TOKEN" \
                -d "{\"lock_reason\": \"resolved\"}" \
                "https://api.github.com/repos/$REPO_NAME/issues/$PR_NUMBER/lock" || echo "Failed to lock PR #$PR_NUMBER"

              echo "Locked pull request #$PR_NUMBER in $REPO_NAME."

              # Deleta o pull request (se aplicável)
              curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER" || echo "Failed to delete PR #$PR_NUMBER"

              echo "Deleted pull request #$PR_NUMBER in $REPO_NAME."
            done
          done
