name: Auto Close, Delete, and Lock Pull Requests

on:
  pull_request:
    types: [opened, reopened]  # Executa automaticamente quando um PR é aberto ou reaberto

permissions:
  contents: write
  pull-requests: write

jobs:
  close_lock_prs:
    runs-on: ubuntu-latest

    steps:
      - name: Close, Lock Pull Requests
        env:
          PR_TOKEN: ${{ secrets.PULL_REQUESTS_TOKEN }}  # Token para autenticação
          GITHUB_USER: ${{ github.actor }}  # Usuário que forneceu o token
        run: |
          ORG="cyonicsolutions-cluster"
          REPO="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          CLOSE_MESSAGE="**Pull requests from outside the organization are not accepted.**\n\nPlease visit https://github.com/getcyonic/$REPO/pulls and submit your pull request there with the same content.\nThank you!"

          # Verifica se o token está definido
          if [ -z "$PR_TOKEN" ]; then
            echo "PR_TOKEN is not set. Exiting..."
            exit 1
          fi

          echo "Pull Request #$PR_NUMBER opened by $PR_AUTHOR in repository $REPO"

          # Comenta no PR com a mensagem de fechamento
          curl -s -X POST -H "Authorization: token $PR_TOKEN" \
            -d "{\"body\": \"$CLOSE_MESSAGE\"}" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments"

          # Fecha o PR
          curl -s -X PATCH -H "Authorization: token $PR_TOKEN" \
            -d "{\"state\": \"closed\"}" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER"

          echo "Closed pull request #$PR_NUMBER in $REPO."

          # Trava a conversa (lock)
          curl -s -X PUT -H "Authorization: token $PR_TOKEN" \
            -d "{\"lock_reason\": \"resolved\"}" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/lock"

          echo "Locked pull request #$PR_NUMBER in $REPO."
