name: Check All Repos for Pull Requests

on:
  schedule:
    - cron: '0 * * * *' # Executa a cada hora (a cada 60 minutos)
  workflow_dispatch:

jobs:
  check_prs:
    runs-on: ubuntu-latest

    steps:
      - name: Check repositories in the organization
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # O token padrão do GitHub Actions
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Seu token pessoal com permissões
        run: |
          ORG="cyonicsolutions-cluster"
          PR_MESSAGE="This repository only accepts mirror pushes. Pull requests cannot be accepted."

          # Obter a lista de repositórios na organização
          repos=$(curl -s -H "Authorization: token $PERSONAL_TOKEN" "https://api.github.com/orgs/$ORG/repos?per_page=100" | jq -r '.[].full_name')

          for repo in $repos; do
            echo "Checking repository: $repo"

            # Obter PRs abertos
            prs=$(curl -s -H "Authorization: token $PERSONAL_TOKEN" "https://api.github.com/repos/$repo/pulls" | jq -r '.[].number')

            for pr in $prs; do
              echo "Found open PR: $pr in $repo"

              # Comentar no PR
              curl -s -X POST -H "Authorization: token $PERSONAL_TOKEN" \
                -d "{\"body\": \"$PR_MESSAGE\"}" \
                "https://api.github.com/repos/$repo/issues/$pr/comments"

              # Fechar o PR
              curl -s -X PATCH -H "Authorization: token $PERSONAL_TOKEN" \
                -d "{\"state\": \"closed\"}" \
                "https://api.github.com/repos/$repo/pulls/$pr"

              # Deletar o PR
              curl -s -X DELETE -H "Authorization: token $PERSONAL_TOKEN" \
                "https://api.github.com/repos/$repo/pulls/$pr"
            done
          done
