name: Auto Close and Delete Issues

on:
  issues:
    types: [opened] # Executa automaticamente quando uma issue é aberta
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  close_and_delete_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Close and Delete Issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }} # Usuário que forneceu o token
        run: |
          ORG="cyonicsolutions-cluster"
          REPO="${{ github.repository }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          ISSUE_AUTHOR="${{ github.event.issue.user.login }}"
          CLOSE_MESSAGE="**Issue reporting is not accepted.** Please visit https://github.com/getcyonic/$REPO/issues and submit your issue report there with the same content.\nThank you!"

          # Verifica se o token está definido
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "GITHUB_TOKEN is not set. Exiting..."
            exit 1
          fi

          echo "Issue #$ISSUE_NUMBER opened by $ISSUE_AUTHOR in repository $REPO"

          # Comenta na issue com a mensagem de fechamento
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"body\": \"$CLOSE_MESSAGE\"}" \
            "https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/comments"

          # Fecha a issue
          curl -s -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"state\": \"closed\"}" \
            "https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER"

          echo "Closed issue #$ISSUE_NUMBER in $REPO."

          # Deleta a issue
          curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER"

          echo "Deleted issue #$ISSUE_NUMBER from $REPO."
