name: Auto Close, Delete, and Lock Pull Requests

on:
  pull_request_target:
    types: [opened, reopened]  # Executa automaticamente quando um pull request é reaberto

permissions:
  contents: write
  pull-requests: write

jobs:
  close_delete_lock_pull_requests:
    runs-on: ubuntu-latest

    steps:
      - name: Close, Delete, and Lock Pull Requests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Certifique-se de que este token esteja correto
        run: |
          REPO="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          CLOSE_MESSAGE="**Pull request submissions are not accepted.**\n\nPlease visit https://github.com/getcyonic/$REPO/pulls and submit your pull request there with the same content.\nThank you!"

          echo "Processing Pull Request #$PR_NUMBER opened by $PR_AUTHOR in repository $REPO"

          # Comenta no pull request
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"body\": \"$CLOSE_MESSAGE\"}" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments" || echo "Failed to comment on pull request #$PR_NUMBER"

          # Fecha o pull request
          curl -s -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"state\": \"closed\"}" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" || echo "Failed to close PR #$PR_NUMBER"

          echo "Closed pull request #$PR_NUMBER in $REPO."

          # Bloqueia a conversa
          curl -s -X PUT -H "Authorization: token $GITHUB_TOKEN" \
            -d "{\"lock_reason\": \"resolved\"}" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/lock" || echo "Failed to lock PR #$PR_NUMBER"

          echo "Locked pull request #$PR_NUMBER in $REPO."

          # Deleta o pull request (se aplicável)
          curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" || echo "Failed to delete PR #$PR_NUMBER"

          echo "Deleted pull request #$PR_NUMBER in $REPO."
