name: Update README Projects

on:
  push:
    branches:
      - main

env:
  GITHUB_USER: cyonicsolutions-cluster

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v2

      - name: Obter projetos do GitHub
        id: get_repos
        run: |
          curl -s "https://api.github.com/users/${{ env.GITHUB_USER }}/repos" | jq -r --arg user "${{ env.GITHUB_USER }}" '.[] | "<details>\n<summary>**\($user/\(.name))**</summary>\n<br>\(.description // "This project didn'\''t provide a description")\n<br>\(.html_url)<br></details>"' > projects.yaml

      - name: Atualizar README.md
        run: |
          echo "Atualizando README.md..."
          sed -i '/<!-- <projects> -->/,/<!-- <\/projects> -->/{//!d}; /<!-- <projects> -->/r projects.yaml' README.md

      - name: Commit e push das alterações
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "README Repository Update at $(date +"%Y-%m-%d %H:%M:%S") UTC " || echo "Nenhuma alteração para commit"
          git push
